# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: iap-agent-registry-endpoint-iam-binding-display
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: IAP Agent Registry Endpoint IAM Binding
    source:
      repo: https://github.com/GoogleCloudPlatform/terraform-google-iap-policy.git
      sourceType: git
      dir: /modules/iap-agent-registry-endpoint-iam-binding
  ui:
    input:
      variables:
        agent_engine_effective_ids:
          name: agent_engine_effective_ids
          title: Agent Engine Effective Ids
        condition:
          name: condition
          title: Condition
        endpoint_id:
          name: endpoint_id
          title: Endpoint Id
        location:
          name: location
          title: Location
        members:
          name: members
          title: Members
        project_id:
          name: project_id
          title: Project Id
        role:
          name: role
          title: Role
    runtime:
      outputs:
        iap_policy_id:
          visibility: VISIBILITY_ROOT
